version: '3'
services:
  db:
    image: mysql:8.0.32
    container_name: test_be_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
  app:
    container_name: test_be_api
    build: backend
    ports:
      - '3001:3001'
    working_dir: /app-backend
    command: dev
    volumes:
      - ./backend/src:/app-backend/src
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: backend_test
